import { randomUUID } from "node:crypto";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import type { Bottleneck } from "./bottlenecks";
import type { ReactIssue } from "./react-analyzer";

export const MAX_SUMMARY_BULLETS = 3;
const MAX_BULLET_LENGTH = 180;

export interface Hotspot extends Bottleneck {
  groupingCaller: string;
  supportingFunctionIds: string[];
  /** At most three short bullets describing the expensive work. */
  summary: string[];
}

/** Token accounting for one agent run, summed across all assistant turns. */
export interface TokenUsage {
  /** Tokens sent to the model (excluding cache reads). */
  input: number;
  /** Tokens generated by the model. */
  output: number;
  /** Prompt tokens served from the provider's cache. */
  cacheRead: number;
  /** Tokens written into the provider's cache. */
  cacheWrite: number;
  /** Total tokens as reported by the provider. */
  totalTokens: number;
  /** USD cost reported by the provider (0 when the model has no known pricing). */
  costUsd: number;
}

export interface AnalysisRecord {
  id: string;
  createdAt: number;
  /** Profile working directory. Empty when the upload was removed after analysis. */
  dir: string;
  totalMs: number;
  hotspots: Hotspot[];
  reactIssues: ReactIssue[];
  /** item id -> generated fix prompt (cached after the second agent run). */
  prompts: Record<string, string>;
  /** Token usage of the analyzer agent run. */
  usage: TokenUsage;
  /** item id -> token usage of the agent run that generated that prompt. */
  promptUsage: Record<string, TokenUsage>;
}

export const PROFILE_FILE_NAME = "profile.json";
export const MAX_UPLOAD_BYTES = 25 * 1024 * 1024;

const RECORD_TTL_MS = 60 * 60 * 1000;
const MAX_RECORDS = 24;

const records = new Map<string, AnalysisRecord>();

function baseDir(): string {
  return path.join(tmpdir(), "perf-ai-profiles");
}

export async function createAnalysisFiles(profile: File): Promise<{ id: string; dir: string }> {
  const id = randomUUID();
  const dir = path.join(baseDir(), id);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, PROFILE_FILE_NAME), Buffer.from(await profile.arrayBuffer()));
  return { id, dir };
}

function pruneExpired(): void {
  const now = Date.now();
  for (const [id, record] of records) {
    if (now - record.createdAt > RECORD_TTL_MS) {
      void destroyRecord(id);
    }
  }
}

export function getRecord(id: string): AnalysisRecord | undefined {
  pruneExpired();
  return records.get(id);
}

export function putRecord(record: AnalysisRecord): void {
  pruneExpired();
  records.set(record.id, record);
  if (records.size > MAX_RECORDS) {
    const oldestFirst = [...records.values()].sort((a, b) => a.createdAt - b.createdAt);
    for (const record of oldestFirst.slice(0, records.size - MAX_RECORDS)) {
      void destroyRecord(record.id);
    }
  }
}

export async function destroyRecord(id: string, dir?: string): Promise<void> {
  const record = records.get(id);
  if (record) records.delete(id);
  const target = record?.dir ?? dir;
  if (!target) return;
  await rm(target, { recursive: true, force: true }).catch(() => undefined);
}

function splitSummaryText(text: string): string[] {
  const trimmed = text.trim();
  if (!trimmed) return [];
  const lines = trimmed.split(/\n+/).map((line) => line.replace(/^[-*•\d.)]+\s+/, "").trim()).filter(Boolean);
  if (lines.length > 1) return lines;
  return trimmed.split(/(?<=[.!?])\s+/).map((part) => part.trim()).filter(Boolean);
}

/** Accept an array, a prose string, or missing text; always return at most three bullets. */
export function normalizeSummary(raw: unknown, fallback: string[]): string[] {
  const source = Array.isArray(raw)
    ? raw.filter((item): item is string => typeof item === "string")
    : typeof raw === "string"
      ? splitSummaryText(raw)
      : [];
  const bullets = source
    .map((item) => item.replace(/^[-*•]\s+/, "").trim())
    .filter(Boolean)
    .slice(0, MAX_SUMMARY_BULLETS)
    .map((item) => (item.length > MAX_BULLET_LENGTH ? `${item.slice(0, MAX_BULLET_LENGTH - 1)}…` : item));
  return bullets.length > 0 ? bullets : fallback;
}

/** Keep measured groups authoritative; the agent only supplies explanations. */
export function normalizeHotspots(raw: unknown, totalMs: number, groups: Bottleneck[]): { hotspots: Hotspot[]; totalMs: number } {
  const annotations = new Map<string, Record<string, unknown>>();
  for (const entry of Array.isArray(raw) ? raw : []) {
    if (!entry || typeof entry !== "object") continue;
    const candidate = entry as Record<string, unknown>;
    if (typeof candidate.id === "string" && !annotations.has(candidate.id)) annotations.set(candidate.id, candidate);
  }
  return {
    totalMs,
    hotspots: groups.map((group) => {
      const candidate = annotations.get(group.id);
      const ids = candidate?.supportingFunctionIds;
      const functionIds = new Set(group.functions.map((fn) => fn.id));
      // Reject ungrounded annotations, including reports extracted from plain text.
      const validEvidence = Array.isArray(ids) && ids.length > 0 && ids.length <= 8
        && ids.every((id) => typeof id === "string" && functionIds.has(id))
        && ids.includes(group.functions[0]?.id);
      const title = typeof candidate?.title === "string" ? candidate.title.trim() : "";
      const annotation = validEvidence && title.length > 0 && title.length <= 120 ? candidate : undefined;
      const heaviest = group.functions.slice(0, MAX_SUMMARY_BULLETS);
      const fallbackTitle = heaviest.map((fn) => fn.title).join(" / ") || "Sampled CPU work";
      const fallbackSummary = heaviest.map((fn) => `${fn.title} (${Math.round(fn.selfTimeMs)} ms self time)`);
      return {
        ...group,
        groupingCaller: group.title,
        title: annotation ? title : fallbackTitle,
        supportingFunctionIds: annotation ? [...new Set(ids as string[])] : heaviest.map((fn) => fn.id),
        summary: normalizeSummary(annotation?.summary, fallbackSummary),
      };
    }).sort((a, b) => b.combinedTimeMs - a.combinedTimeMs),
  };
}

/** Card results keep top function names; stacks stay on the server record for prompt generation. */
export function clientHotspots(hotspots: Hotspot[]): Hotspot[] {
  return hotspots.map((hotspot) => ({
    ...hotspot,
    stack: [],
    functions: hotspot.functions.slice(0, MAX_SUMMARY_BULLETS).map((fn) => ({
      id: fn.id,
      title: fn.title,
      selfTimeMs: fn.selfTimeMs,
      percentOfGroup: fn.percentOfGroup,
      stack: [],
    })),
  }));
}
